create table if not exists users (
	id         varchar(255) primary key,
	email      text not null,
	created_at timestamp not null default (now() at time zone 'utc'),
	updated_at timestamp not null default (now() at time zone 'utc')
);

create table if not exists domains (
	id          int primary key generated by default as identity,
	user_id     varchar(255) not null,
	domain_name text not null,
	issued_by   text,
	dns_names   text,
	ip_address  text,
	signature   text,
	status      text,
	expires_at  timestamp,
	checked_at  timestamp,
	latency     int,
	created_at  timestamp not null default (now() at time zone 'utc'),
	updated_at  timestamp not null default (now() at time zone 'utc'),
	constraint fk_domains_user_id foreign key (user_id) references users (id) on delete cascade,
	constraint uq_domains_user_id_domain_name unique (user_id, domain_name)
);

create table if not exists settings (
	id            int primary key generated by default as identity,
	user_id       varchar(255) not null,
	webhook_url   text not null,
	remind_before int not null,
	constraint fk_settings_user_id
		foreign key (user_id)
		references users (id)
		on delete cascade,
	constraint uq_settings_user_id
		unique (user_id)
);

create table if not exists notifications (
	id                int primary key generated by default as identity,
	user_id           varchar(255) not null,
	domain_id         int not null,
	notification_type int not null,
	body              text not null,
	due               timestamp not null,
	delivered_at      timestamp,
	attempts          int not null default 0,
	deleted_after     timestamp not null,
	created_at        timestamp not null default (now() at time zone 'utc'),
	constraint fk_notifications_user_id
		foreign key (user_id)
		references users (id)
		on delete cascade,
	constraint fk_notifications_domain_id
		foreign key (domain_id)
		references domains (id)
		on delete cascade,
	constraint uq_notifications_domain_id_due
		unique (domain_id, due)
);
