create table if not exists notifications (
	id                int primary key generated by default as identity,
	user_id           varchar(255) not null,
	domain_id         int not null,
	notification_type int not null,
	body              text not null,
	due               timestamp not null,
	delivered_at      timestamp,
	attempts          int not null default 0,
	deleted_after     timestamp not null,
	created_at        timestamp not null default (now() at time zone 'utc'),
	constraint fk_notifications_user_id
		foreign key (user_id)
		references users (id)
		on delete cascade,
	constraint fk_notifications_domain_id
		foreign key (domain_id)
		references domains (id)
		on delete cascade,
	constraint uq_notifications_domain_id_due
		unique (domain_id, due)
);
