create table if not exists users (
	id         varchar(255) primary key,
	email      text not null,
	created_at timestamp not null default (now() at time zone 'utc'),
	updated_at timestamp not null default (now() at time zone 'utc')
);

create table if not exists domains (
	id          int primary key generated by default as identity,
	user_id     varchar(255) not null,
	domain_name text not null,
	issued_by   text,
	dns_names   text,
	ip_address  text,
	status      text,
	expires_at  timestamp,
	checked_at  timestamp,
	latency     int,
	created_at  timestamp not null default (now() at time zone 'utc'),
	updated_at  timestamp not null default (now() at time zone 'utc'),
	constraint fk_domains_user_id foreign key (user_id) references users (id) on delete cascade,
	constraint uq_domains_user_id_domain_name unique (user_id, domain_name)
);
