create table if not exists settings (
	id            int primary key generated by default as identity,
	user_id       varchar(255) not null,
	webhook_url   text not null,
	remind_before int not null,
	constraint fk_settings_user_id
		foreign key (user_id)
		references users (id)
		on delete cascade,
	constraint uq_settings_user_id
		unique (user_id)
);
