name: neverexpire-dev
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        UID: ${USER_ID}
        GID: ${GROUP_ID}
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      migrate:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis
  postgres:
    image: postgres:17.4
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - "${POSTGRES_HOST_PORT}:${POSTGRES_DOCKER_PORT}"
    volumes:
      - db:/var/lib/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
  migrate:
    image: migrate/migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./db/migrations:/migrations
    command:
      [
        "-path",
        "/migrations/",
        "-database",
        "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_DOCKER_PORT}/${POSTGRES_DB}?sslmode=disable",
        "up",
      ]

volumes:
  redis:
  db:
