name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4
      - name: "Setup docker buildx"
        uses: docker/setup-buildx-action@v3
      - name: "Log in to Github Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build image and push it to the registry"
        run: |
          docker build -t ghcr.io/lionpuro/neverexpire:latest .
          docker push ghcr.io/lionpuro/neverexpire:latest
      - name: "Deploy"
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /srv/neverexpire
            git pull
            docker compose -f ./compose.yaml pull
            docker compose -f ./compose.yaml up --build -d
